### ISSUE TITLE
Design/Code Review 1

### ISSUE THREAD

**Issue by esajdak** [jeevarg/fishingspots#3]
# Design/Code Review 1
​
## Project: Fishing Spots
​
### Developer: Jeeva
​
### Reviewer: Elizabeth
​
It seems like you have a great idea of what you plan on doing, just be cautious not to get behind (I'm very good at procrastinating and know how frustrating it can be when you're behind).

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Problem statement does a good job describing what the project is about, great idea as I also haven't seen many sites that offer this. Your last sentence seems to mention rating a spot twice, possibly reword that.  |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Might consider adding more fields in "add spot" page. Check for typos in the "about" page. Overall great screen designs. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Databases/models not yet created. It seems like you have a good understanding of where you plan to go with this, I would suggest taking the opportunities for weekly activities to be done in your project- it's really helped me to keep up! |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.| Implemented .gitignore. Logging has not been set up yet. No code to look at quite yet. |

**Comment by jeevarg** [comment]
Hi @esajdak , thank you for the feedback. I agree with you on implementing the weekly exercises in the project to save time and will try to do that.
