### ISSUE TITLE
Database Design Review - Week 7

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jeevarg/fishingspots#4]
@jeevarg Your design is looking very good. I just have two suggestions after reviewing your ERD.

- [ ] For tomcat authentication to work, the role table will need the email field (assuming this is the value the user will enter to log in to the application). I know this is not great database design!  Refer to my 9/30 post in #indie-project in slack for details. This is something you can take care of when you complete the week 7 work in your project.
- [ ] I don't think the review id should be on the spot table, as a spot could have 0 to many reviews.

**Comment by jeevarg** [comment]
@pawaitemadisoncollege Should the password field go in the role table too?

**Comment by pawaitemadisoncollege** [comment]
Nope! https://mad-java-ent-f20.slack.com/archives/C019P69DW69/p1601473757007700
