### ISSUE TITLE
AWS Users Display Results

### ISSUE THREAD

**Issue by jeevarg** [jeevarg/fishingspots#6]
@pawaitemadisoncollege
I finished the week6 AWS exercise. I was updating the password in database.properties file but not in hibernate.cfg.xml file and this kept giving me that error "hibernate.dialect not set". What I did was a very simple mistake but It took me 2 days to figure it out.

**Comment by jeevarg** [comment]
Sorry Paula, had to delete the previous commit because of the sensitive files and do a re-commit without those files.

**Comment by pawaitemadisoncollege** [comment]
@jeevarg It's always the "simple" mistakes, isn't it?! We've all been there!

You can close this up!
