### ISSUE TITLE
week7 work complete with screenshots included

### ISSUE THREAD

**Issue by jeevarg** [jeevarg/fishingspots#7]
@pawaitemadisoncollege - Completed week7 work along with the feedback for Caroline's Presentation.

**Comment by pawaitemadisoncollege** [comment]
You have a good start adding auth to your project @jeevarg 

- [ ] As you add functionality to your project, remember to also restrict access to the controllers accessed by the jsps - a savvy user could go directly to the servlet and bypass your current security.
