### ISSUE TITLE
week-8 work complete

### ISSUE THREAD

**Issue by jeevarg** [jeevarg/fishingspots#8]
@pawaitemadisoncollege - week-8 exercise complete. Implemented ZipCodeByRadiusAPI REST webservice.

**Comment by pawaitemadisoncollege** [comment]
Great job with this @jeevarg!

I'm sure these are on your radar, but just a couple things to remember as you continue working with this.

- [ ] Put the api base url and key in a properties file: https://github.com/jeevarg/fishingspots/blob/d8173021bb4a8b2a44d5ca5b939264fe01814721/src/main/java/com/fishingspots/persistence/ZipCodeAPIDao.java#L22
and https://github.com/jeevarg/fishingspots/blob/d8173021bb4a8b2a44d5ca5b939264fe01814721/src/main/java/com/fishingspots/persistence/ZipCodeAPIDao.java#L33
- [ ] Update the method signature to receive a zip code.https://github.com/jeevarg/fishingspots/blob/d8173021bb4a8b2a44d5ca5b939264fe01814721/src/main/java/com/fishingspots/persistence/ZipCodeAPIDao.java#L30
